version: '3.8'

services:
  redis-server:
    image: redis:7
    container_name: redis-server
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  backend:
    external: true
