services:
  api-server:
    build: 
      context: .
      dockerfile: ./Dockerfile-prod
    ports:
      - 4000:4000
    depends_on:
      cache-server:
        condition: service_healthy
    environment:
      - SPRING_JWT_SECRET=${SPRING_JWT_SECRET}
        CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
        CLOUD_AWS_CREDENTIALS_SECRET_KEY=${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
        CLOUD_AWS_REGION_STATIC=${CLOUD_AWS_REGION_STATIC}
        CLOUD_AWS_S3_BUCKET=${CLOUD_AWS_S3_BUCKET}
  cache-server:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10

