version: '3.8'

services:
  api-blue:
    image: ratsche/dodorose:latest
    container_name: app-blue
    environment:
      - LANG=ko_KR.UTF-8
      - HTTP_PORT=8080
      - SPRING_REDIS_HOST=redis-server
    ports:
      - "4000:8080"
    networks:
      - backend

networks:
  backend:
    external: true
