version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/ubuntu/data/prometheus:/prometheus
    networks:
      - monitoring
      - backend   # 앱 연결 위해 추가

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000:1000"
    restart: always
    ports:
      - "3100:3000"
    volumes:
      - /home/ubuntu/data/grafana.ini:/etc/grafana/grafana.ini
      - /home/ubuntu/data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
  backend:
    external: true
