version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/prometheus:/etc/prometheus
      - /home/ubuntu/data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=https://api.dodorose.com/monitor/prometheus'
      - '--web.route-prefix=/'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3100:3000"
    volumes:
      - /home/ubuntu/data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://api.dodorose.com/monitor/grafana
      - GF_SERVER_DOMAIN=api.dodorose.com
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_SECURITY_COOKIE_SAMESITE=lax
    depends_on:
      - prometheus
    networks:
      - monitoring
      - backend

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
  backend:
    external: true