version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/ubuntu/data/prometheus:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000:1000"
    restart: always
    ports:
      - "3100:3000"
    volumes:
      - /home/ubuntu/data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=api.dodorose.com
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/monitor/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
