name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Replace application.yml
        run: |
          echo "$APPLICATION_YML" > src/main/resources/application.yml
          echo "$APPLICATION_OAUTH2_YML" > src/main/resources/application-oauth2.yml

      - name: Build JAR
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Docker Build & Push
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build --no-cache -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest

      - name: Generate SSH Key File
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY_BASE64 }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem

      - name: Copy deploy.sh to EC2
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no ./deploy.sh \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/CrystalRose-back/deploy.sh

      - name: Copy monitoring.sh to EC2
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no ./monitoring.sh \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/CrystalRose-back/monitoring.sh

      - name: Copy Prometheus Config to EC2
        run: |
          echo "$APROMETHEUS_YML" > aprometheus.yml
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "mkdir -p /home/ubuntu/prometheus"
          scp -i private_key.pem -o StrictHostKeyChecking=no ./aprometheus.yml \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/prometheus/prometheus.yml

      - name: Copy Monitoring Compose to EC2
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no ./infra/docker-compose.monitoring.yml \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/docker-compose.monitoring.yml

      - name: Deploy via SSH
        env:
          APPLICATION_YML: ${{ secrets.APPLICATION_YML }}
          APPLICATION_OAUTH2_YML: ${{ secrets.APPLICATION_OAUTH2_YML }}
          APROMETHEUS_YML: ${{ secrets.APROMETHEUS_YML }}
          SPRING_JWT_SECRET: ${{ secrets.SPRING_JWT_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUD_AWS_CREDENTIALS_SECRET_KEY }}
          CLOUD_AWS_REGION_STATIC: ${{ secrets.CLOUD_AWS_REGION_STATIC }}
          CLOUD_AWS_S3_BUCKET: ${{ secrets.CLOUD_AWS_S3_BUCKET }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_MAIL_HOST: ${{ secrets.SPRING_MAIL_HOST }}
          SPRING_MAIL_PORT: ${{ secrets.SPRING_MAIL_PORT }}
          SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
          FILE_UPLOAD_DIR: ${{ secrets.FILE_UPLOAD_DIR }}
          IMG_UPLOAD_DIR: ${{ secrets.IMG_UPLOAD_DIR }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SPRING_PROFILES_INCLUDE: ${{ secrets.SPRING_PROFILES_INCLUDE }}
          OAUTH2_FRONTEND_URL: ${{ secrets.OAUTH2_FRONTEND_URL }}
          NAVER_REDIRECT_URI: ${{ secrets.NAVER_REDIRECT_URI }}
          KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}
          GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          SPRING_REDIS_HOST: ${{ secrets.SPRING_REDIS_HOST }}
          SPRING_DATA_REDIS_PORT: ${{ secrets.SPRING_DATA_REDIS_PORT }}
          CLOUD_AWS_CLOUDFRONT_DOMAIN: ${{ secrets.CLOUD_AWS_CLOUDFRONT_DOMAIN }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_REDIRECT_URI: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_REDIRECT_URI }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI }}
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} <<EOF
            cd /home/ubuntu/CrystalRose-back

            git reset --hard HEAD
            git fetch origin
            git reset --hard origin/main

            echo "[ENV] 환경 파일 설정"
            rm -f .env
            touch .env

            # Spring Boot 환경 변수 주입
            echo "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME" >> .env
            echo "DOCKERHUB_REPO=$DOCKERHUB_REPO" >> .env
            echo "SPRING_JWT_SECRET=$SPRING_JWT_SECRET" >> .env
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
            echo "CLOUD_AWS_REGION_STATIC=$CLOUD_AWS_REGION_STATIC" >> .env
            echo "CLOUD_AWS_S3_BUCKET=$CLOUD_AWS_S3_BUCKET" >> .env
            echo "SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL" >> .env
            echo "SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME" >> .env
            echo "SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD" >> .env
            echo "SPRING_MAIL_HOST=$SPRING_MAIL_HOST" >> .env
            echo "SPRING_MAIL_PORT=$SPRING_MAIL_PORT" >> .env
            echo "SPRING_MAIL_USERNAME=$SPRING_MAIL_USERNAME" >> .env
            echo "SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD" >> .env
            echo "FILE_UPLOAD_DIR=$FILE_UPLOAD_DIR" >> .env
            echo "IMG_UPLOAD_DIR=$IMG_UPLOAD_DIR" >> .env
            echo "KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID" >> .env
            echo "KAKAO_CLIENT_SECRET=$KAKAO_CLIENT_SECRET" >> .env
            echo "NAVER_CLIENT_ID=$NAVER_CLIENT_ID" >> .env
            echo "NAVER_CLIENT_SECRET=$NAVER_CLIENT_SECRET" >> .env
            echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
            echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
            echo "SERVER_PORT=$SERVER_PORT" >> .env
            echo "SPRING_PROFILES_INCLUDE=$SPRING_PROFILES_INCLUDE" >> .env
            echo "OAUTH2_FRONTEND_URL=$OAUTH2_FRONTEND_URL" >> .env
            echo "NAVER_REDIRECT_URI=$NAVER_REDIRECT_URI" >> .env
            echo "KAKAO_REDIRECT_URI=$KAKAO_REDIRECT_URI" >> .env
            echo "GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI" >> .env
            echo "SPRING_REDIS_HOST=$SPRING_REDIS_HOST" >> .env
            echo "SPRING_DATA_REDIS_PORT=$SPRING_DATA_REDIS_PORT" >> .env
            echo "CLOUD_AWS_CLOUDFRONT_DOMAIN=$CLOUD_AWS_CLOUDFRONT_DOMAIN" >> .env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID=$SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID" >> .env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET=$SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET" >> .env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI=$SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI" >> .env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID=$SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID" >> .env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET=$SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET" >> .env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_REDIRECT_URI=$SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_REDIRECT_URI" >> .env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=$SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID" >> .env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=$SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET" >> .env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI=$SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI" >> .env
            echo "GF_SECURITY_ADMIN_USER=$GF_SECURITY_ADMIN_USER" >> .env
            echo "GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD" >> .env

            echo "[DEPLOY] 애플리케이션 배포"
            chmod +x ./deploy.sh
            ./deploy.sh

            echo "[MONITORING] Prometheus & Grafana 배포"
            docker-compose -f /home/ubuntu/docker-compose.monitoring.yml up -d
          EOF