name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate SSH Key File
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY_BASE64 }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem

      - name: Configure AWS credentials for CLI
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.CLOUD_AWS_CREDENTIALS_SECRET_KEY }}" >> ~/.aws/credentials

      - name: SSH Deploy to EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            cd /home/ubuntu/CrystalRose-back || git clone git@github.com:50104/CrystalRose-back.git && cd CrystalRose-back

            git fetch origin
            git reset --hard origin/main

            aws s3 cp s3://crystalrose-web/config/application.yml src/main/resources/application.yml
            aws s3 cp s3://crystalrose-web/config/application-oauth2.yml src/main/resources/application-oauth2.yml

            chmod +x ./gradlew
            ./gradlew clean build --no-daemon

            sudo fuser -k -n tcp 4000 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
          EOF
